openapi: 3.0.3
info:
  version: 1.0.0
  title: REST API
  description: ""
servers:
  - url: http://localhost:7000/
paths:
  /version:
    get:
      description: "versionInfo"
      summary: ""
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  name:
                    type: string
                  version:
                    type: string
  /animal:
    get:
      description: "動物の判定"
      summary: 足があるかどうか
      operationId: animal
      requestBody:
        description: 動物の特徴
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "dog"
                hasLegs:
                  type: boolean
                  example: true
              required:
                - name
                - hasLegs
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
